### ISSUE TITLE
Provide a path when uploading

### ISSUE THREAD

**Issue by jonahbardos** [g2nb/ipyuploads#3]
The widget automatically uploads to the current working directory. 

- [x] Have an option to upload to a custom directory.

**Comment by jonahbardos** [comment]
Would you like me to make a pull request? @tmtabor 
I can do that this week.

**Comment by tmtabor** [comment]
Sure! That would be great.

**Comment by jonahbardos** [comment]
@tmtabor I have the changes, but I am unable to push my branch for pull request. :/

**Comment by jonahbardos** [comment]
My message cut off. I need permission to push my branch for pull request.

**Comment by jonahbardos** [comment]
Test code I used @tmtabor 

```python
import ipyuploads
import ipywidgets

output = ipywidgets.Output()

def chunk_complete(name, count, total):
    """Callback to be executed when a chunk finishes uploading
    
       name - Name of the file being uploaded
       count - A counter of which chunk just finished uploading
       total - The total number of chunks in this file"""
    with output:
        print(f'CHUNK CALLBACK! {name} {count} {total}')

def file_complete(name):
    """Callback to be executed when a file finishes uploading
    
       name - Name of the file that was just uploaded"""
    with output:
        print('FILE CALLBACK! ' + name)

def all_files_complete(metadatas):
    """Callback to be executed once all selected files finish uploading
    
       metadatas - A list of metadata objects, one for each file. Each contains:
                   { 'name': 'the file's name', 
                     'type': 'mime-type of the file', 
                     'last_modified': last modified data as an integer 
                                      (number of milliseconds since the epoch) }"""
    with output:
        print(f'ALL FILES CALLBACK! {metadatas}')

custom_path = "./test_folder"
a = ipyuploads.Upload(accept='txt',           # Accept only text files
                  multiple=True,          # Upload multiple files at once
                  disabled=False,          # Disable the widget
                  icon='cloud-upload',    # Change the upload icon
                  button_stye='primary',  # Change the button style
                  error='Bad Error',      # Set the error message
                  busy=False,             # Whether an upload is in progress
                  chunk_complete=chunk_complete,     # Callback when a chunk upload completes
                  file_complete=file_complete,      # Callback when a file upload completes
                  all_files_complete=all_files_complete, # Callback when all files complete
                  custom_path=custom_path  
                  )

a.custom_path
display(a, output)
```

**Comment by tmtabor** [comment]
You should be able to [fork](https://github.com/g2nb/ipyuploads/fork) the repository, check in the code to your fork and then [send a pull request](https://github.com/g2nb/ipyuploads/compare) from your fork back to the upstream repo. At least, that's the pull request workflow I'm familiar with on Github.

**Comment by jonahbardos** [comment]
> You should be able to [fork](https://github.com/g2nb/ipyuploads/fork) the repository, check in the code to your fork and then [send a pull request](https://github.com/g2nb/ipyuploads/compare) from your fork back to the upstream repo. At least, that's the pull request workflow I'm familiar with on Github.

Ahh copy that. Done. https://github.com/g2nb/ipyuploads/pull/4

**Comment by jonahbardos** [comment]
Any chance your team can have a new version `.0..2.3` deployed next week once the PR gets reviewed/approved? I currently have to modify the code from pip install to get it working to use custom paths. @tmtabor

**Comment by tmtabor** [comment]
No problem. I'll get it reviewed and released on Monday.

**Comment by jonahbardos** [comment]
Thanks for the quick reply from you and your team @tmtabor !
