### ISSUE TITLE
Version 0.2.3 ipyuploads release on PyPI

### ISSUE THREAD

**Issue by jonahbardos** [g2nb/ipyuploads#5]
Hey @tmtabor 
Just creating an issue for documentation. Please release when you can on PyPi. Thank you!

Relates to:
https://github.com/g2nb/ipyuploads/pull/4

**Comment by tmtabor** [comment]
The new release was pushed to PyPI a few hours ago: https://pypi.org/project/ipyuploads/

**Comment by jonahbardos** [comment]
Thanks @tmtabor ! I was thrown off by this on github
![image](https://github.com/user-attachments/assets/1f6f2dd2-717f-4a42-bed0-b2ddd590d3a5)

**Comment by tmtabor** [comment]
Yeah. I pushed a release to PyPI but didn't do a GitHub release as well. Once of these days I need to automate that as a GitHub action. Regardless, I've done the GitHub release not, too!

**Comment by jonahbardos** [comment]
Thanks!
